apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: {{ .Values.image.cast_service.repository }}:{{ .Values.image.cast_service.tag }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "postgresql://cast_db_username:cast_db_password@cast-db:5432/cast_db_dev"
