apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: samuellmfa/cast-service:v.9.0
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              value: "cast_db_username"
            - name: POSTGRES_PASSWORD
              value: "cast_db_password"
            - name: POSTGRES_DB
              value: "cast_db_dev"
            - name: DB_HOST
              value: "cast-db"
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
