apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: cast-db
          image: postgres:12.1-alpine
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-data
          env:
            - name: POSTGRES_USER
              value: "cast_db_username"
            - name: POSTGRES_PASSWORD
              value: "cast_db_password"
            - name: POSTGRES_DB
              value: "cast_db_dev"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-cast
