apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: {{ .Values.image.movie_service.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          env:
            - name: DB_USERNAME
              value: "movie_db_username"
            - name: DB_PASSWORD
              value: "movie_db_password"
            - name: DB_NAME
              value: "movie_db_dev"
            - name: DB_HOST
              value: "movie-db"
            - name: DB_PORT
              value: "5432"

