apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-movie 
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
