apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8085
          volumeMounts:
            - name: nginx-storage
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf  # Adjust based on your volume content
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteMany  # Adjust based on your requirements
  resources:
    requests:
      storage: 1Gi  # Adjust based on your requirements

