apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 8001  # Exposed port on the Service
      targetPort: 8000  # Port the Deployment container is listening on
